(() => {
  'use strict';
  if (window.__fuelDashboardV12Loaded) return;
  window.__fuelDashboardV12Loaded = true;

  const STORAGE_KEY_FALLBACK = 'fuelTrackerData';
  const state = { view: 'efficiency', lastRefresh: null, reloadingForUpgrade: false };
  const $ = (id) => document.getElementById(id);

  function storageKey(){ return typeof window.STORAGE_KEY === 'string' ? window.STORAGE_KEY : STORAGE_KEY_FALLBACK; }
  function safeLoadData(){
    const raw=localStorage.getItem(storageKey());
    if(!raw)return {data:[],parseError:null};
    try{const parsed=JSON.parse(raw);return Array.isArray(parsed)?{data:parsed,parseError:null}:{data:[],parseError:'Stored database is not in the expected list format.'};}
    catch(error){return {data:[],parseError:'Stored database contains invalid JSON and cannot be read safely.'};}
  }
  function validDate(value){const d=new Date(value);return Number.isNaN(d.getTime())?null:d;}
  function fingerprint(entry){return [entry?.dateTime||'',Number(entry?.mileage)||0,Number(entry?.volume)||0,Number(entry?.cost)||0,String(entry?.currency||'').toUpperCase(),String(entry?.location||'').trim().toLowerCase()].join('|');}
  function shortEntry(entry){const date=validDate(entry?.dateTime);const dateText=date?date.toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):'unknown date';const odo=Number(entry?.mileage);return `${dateText}${Number.isFinite(odo)?` • ${odo.toLocaleString()} km`:''}`;}

  function validateIntegrity(data,parseError){
    const issues=[];
    if(parseError)issues.push({type:'error',text:parseError,detail:'The working copy cannot be trusted until a valid database is restored.',action:'Use Master Data & Backup → RESTORE / REPLACE and select your latest known-good Master DB backup.',target:'backup'});
    const seen=new Map(),duplicateExamples=[],invalidExamples=[],currencyExamples=[];
    let duplicates=0,invalidRecords=0,currencyWarnings=0;
    data.forEach((entry,index)=>{
      const date=validDate(entry?.dateTime),mileage=Number(entry?.mileage),volume=Number(entry?.volume),cost=Number(entry?.cost),currency=String(entry?.currency||'').toUpperCase(),location=String(entry?.location||'').trim();
      if(!date||!Number.isFinite(mileage)||mileage<0||!Number.isFinite(volume)||volume<=0||!Number.isFinite(cost)||cost<0||!location){invalidRecords++;if(invalidExamples.length<3)invalidExamples.push(shortEntry(entry));}
      if(currency&&!['SGD','MYR'].includes(currency)){currencyWarnings++;if(currencyExamples.length<3)currencyExamples.push(`${shortEntry(entry)} • ${currency}`);}
      const fp=fingerprint(entry);if(seen.has(fp)){duplicates++;if(duplicateExamples.length<3)duplicateExamples.push(shortEntry(entry));}else seen.set(fp,index);
    });
    const chronological=data.map((entry,index)=>({entry,index,date:validDate(entry?.dateTime),mileage:Number(entry?.mileage)})).filter(x=>x.date&&Number.isFinite(x.mileage)&&x.mileage>=0).sort((a,b)=>a.date-b.date);
    let odoRegressions=0;const odoExamples=[];
    for(let i=1;i<chronological.length;i++)if(chronological[i].mileage<chronological[i-1].mileage){odoRegressions++;if(odoExamples.length<3)odoExamples.push(`${shortEntry(chronological[i].entry)} is below previous ${chronological[i-1].mileage.toLocaleString()} km`);}
    if(duplicates)issues.push({type:'warn',text:`${duplicates} possible duplicate ${duplicates===1?'record':'records'}`,detail:duplicateExamples.join('; '),action:'Review Fuel History. If the entries are truly duplicated, delete only the extra copy. Save a Master DB backup first if you are unsure.',target:'history'});
    if(invalidRecords)issues.push({type:'error',text:`${invalidRecords} ${invalidRecords===1?'record has':'records have'} missing or invalid required data`,detail:invalidExamples.join('; '),action:'Review Fuel History, remove the incorrect entry and re-add it with a valid date, odometer, litres, cost and station. If many records are affected, restore a known-good Master DB instead.',target:'history'});
    if(odoRegressions)issues.push({type:'warn',text:`${odoRegressions} odometer sequence ${odoRegressions===1?'regression':'regressions'}`,detail:odoExamples.join('; '),action:'Check the highlighted refuel against your receipt or odometer. Delete and re-add the incorrect entry with the correct mileage.',target:'history'});
    if(currencyWarnings)issues.push({type:'warn',text:`${currencyWarnings} unsupported currency ${currencyWarnings===1?'value':'values'}`,detail:currencyExamples.join('; '),action:'Fuel Tracker currently supports SGD and MYR. Re-add the affected entry using the correct supported currency.',target:'history'});
    const latest=data.map(entry=>({entry,date:validDate(entry?.dateTime)})).filter(x=>x.date).sort((a,b)=>b.date-a.date)[0]||null;
    const level=parseError||invalidRecords?'error':(duplicates||odoRegressions||currencyWarnings?'warn':'healthy');
    return {level,issues,latest,count:data.length};
  }

  function formatDate(date){return date?date.toLocaleString(undefined,{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'No valid data yet';}
  function escapeHtml(value){return String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));}

  function buildUI(){
    const mileageTabs=$('mileageTabs'),spendingTabs=$('spendingTabs');if(!mileageTabs||!spendingTabs)return null;
    const mileagePanel=mileageTabs.closest('.period-panel'),spendingPanel=spendingTabs.closest('.period-panel');if(!mileagePanel||!spendingPanel||mileagePanel.dataset.v12Wrapped)return null;
    mileagePanel.dataset.v12Wrapped='true';spendingPanel.dataset.v12Wrapped='true';
    const spendingSeparator=Array.from(document.querySelectorAll('.section-separator')).find(el=>el.textContent.trim().toLowerCase()==='fuel spending');if(spendingSeparator)spendingSeparator.hidden=true;
    const frame=document.createElement('section');frame.className='unified-dashboard-frame';frame.setAttribute('aria-label','Fuel dashboard');
    frame.innerHTML=`<div class="unified-dashboard-head"><div class="dashboard-switch" role="tablist" aria-label="Dashboard view"><button type="button" class="dashboard-switch-btn active" data-dashboard-view="efficiency" role="tab" aria-selected="true">⛽ Efficiency</button><button type="button" class="dashboard-switch-btn" data-dashboard-view="spending" role="tab" aria-selected="false">💰 Spending</button></div><button type="button" class="dashboard-refresh-btn" id="dashboardRefreshBtn" aria-label="Refresh dashboard, check data and apply available UI update">↻ <span>Refresh</span></button></div><div class="dashboard-refresh-note" id="dashboardRefreshNote">Refresh recalculates data, checks integrity and applies an available app/UI update.</div><div class="dashboard-common-tabs" id="dashboardCommonTabs" aria-label="Dashboard timeframe"><button type="button" class="dashboard-common-tab active" data-common-period="14">14 Days</button><button type="button" class="dashboard-common-tab" data-common-period="month">Monthly</button><button type="button" class="dashboard-common-tab" data-common-period="year">Yearly</button><button type="button" class="dashboard-common-tab" data-common-period="all">All Time</button></div><div class="dashboard-health-strip" id="dashboardHealthStrip" aria-live="polite"><span class="health-dot"></span><span class="health-text">Checking data…</span><span class="health-latest"></span></div><div class="dashboard-view-stage" id="dashboardViewStage"></div><div class="dashboard-view-dots" aria-hidden="true"><span class="active"></span><span></span></div>`;
    mileagePanel.parentNode.insertBefore(frame,mileagePanel);const stage=frame.querySelector('#dashboardViewStage');
    const efficiencyView=document.createElement('div');efficiencyView.className='dashboard-view active';efficiencyView.dataset.view='efficiency';
    const spendingView=document.createElement('div');spendingView.className='dashboard-view';spendingView.dataset.view='spending';stage.append(efficiencyView,spendingView);efficiencyView.appendChild(mileagePanel);spendingView.appendChild(spendingPanel);
    mileageTabs.classList.add('v12-hidden-tabs');spendingTabs.classList.add('v12-hidden-tabs');
    const details=document.createElement('div');details.className='dashboard-health-details';details.id='dashboardHealthDetails';details.hidden=true;details.innerHTML=`<div class="health-detail-grid"><div><span>Records</span><strong id="healthRecordCount">0</strong></div><div><span>Latest ingested</span><strong id="healthLatestIngested">—</strong></div><div><span>Latest odometer</span><strong id="healthLatestOdo">—</strong></div><div><span>Last UI refresh</span><strong id="healthLastRefresh">—</strong></div></div><div class="health-help-title">Data review & actions</div><div class="health-issues" id="healthIssues"></div>`;
    frame.querySelector('#dashboardHealthStrip').insertAdjacentElement('afterend',details);frame.querySelector('#dashboardHealthStrip').setAttribute('role','button');frame.querySelector('#dashboardHealthStrip').setAttribute('tabindex','0');frame.querySelector('#dashboardHealthStrip').setAttribute('aria-expanded','false');return frame;
  }

  function setView(view){state.view=view;document.querySelectorAll('.dashboard-switch-btn').forEach(btn=>{const active=btn.dataset.dashboardView===view;btn.classList.toggle('active',active);btn.setAttribute('aria-selected',active?'true':'false');});document.querySelectorAll('.dashboard-view').forEach(panel=>panel.classList.toggle('active',panel.dataset.view===view));document.querySelectorAll('.dashboard-view-dots span').forEach((dot,index)=>dot.classList.toggle('active',(view==='efficiency'?0:1)===index));}
  function setCommonPeriod(period){document.querySelectorAll('.dashboard-common-tab').forEach(btn=>btn.classList.toggle('active',btn.dataset.commonPeriod===period));document.querySelector(`[data-mileage-period="${period}"]`)?.click();document.querySelector(`[data-spending-period="${period}"]`)?.click();}
  function actionButton(issue){if(!issue.target)return '';const label=issue.target==='backup'?'Open Master Data & Backup':'Review Fuel History';return `<button type="button" class="health-action-btn" data-health-action="${issue.target}">${label}</button>`;}

  function updateHealthUI(result){
    const strip=$('dashboardHealthStrip');if(!strip)return;strip.classList.remove('healthy','warn','error','checking');strip.classList.add(result.level);const label=result.level==='healthy'?'Data healthy':result.level==='warn'?'Review data':'Data integrity issue';strip.querySelector('.health-text').textContent=label;strip.querySelector('.health-latest').textContent=result.latest?`Latest: ${formatDate(result.latest.date)}`:'No ingested records';
    $('healthRecordCount').textContent=String(result.count);$('healthLatestIngested').textContent=result.latest?formatDate(result.latest.date):'—';const latestOdo=result.latest?Number(result.latest.entry?.mileage):NaN;$('healthLatestOdo').textContent=Number.isFinite(latestOdo)?`${latestOdo.toLocaleString()} km`:'—';$('healthLastRefresh').textContent=state.lastRefresh?formatDate(state.lastRefresh):'—';
    $('healthIssues').innerHTML=result.issues.length?result.issues.map(issue=>`<div class="health-issue ${issue.type}"><div class="health-issue-title">${issue.type==='error'?'⚠':'•'} ${escapeHtml(issue.text)}</div>${issue.detail?`<div class="health-issue-detail">Affected: ${escapeHtml(issue.detail)}</div>`:''}<div class="health-resolution"><strong>Action:</strong> ${escapeHtml(issue.action||'Review the affected data and refresh again after correcting it.')}</div>${actionButton(issue)}</div>`).join(''):'<div class="health-issue ok"><div class="health-issue-title">✓ No integrity issues detected.</div><div class="health-resolution">No action required. The latest stored data is ready for dashboard calculations.</div></div>';
    const existingPanel=$('dataStatusPanel');if(existingPanel&&!$('dataIntegrityStatus')){const item=document.createElement('div');item.className='data-status-item';item.innerHTML='<div class="data-status-label">Integrity</div><div class="data-status-value" id="dataIntegrityStatus">—</div>';existingPanel.querySelector('.data-status-grid')?.appendChild(item);}const integrity=$('dataIntegrityStatus');if(integrity){integrity.textContent=label;integrity.classList.toggle('warn',result.level!=='healthy');}
  }

  function scrollToTarget(target){let el=null;if(target==='history')el=$('entriesList')?.closest('.card')||$('entriesList');if(target==='backup')el=document.querySelector('.backup-panel');if(el){el.scrollIntoView({behavior:'smooth',block:'start'});el.classList.add('health-target-flash');setTimeout(()=>el.classList.remove('health-target-flash'),1800);}}
  function waitForControllerChange(timeoutMs=3500){if(!('serviceWorker'in navigator))return Promise.resolve(false);return new Promise(resolve=>{let done=false;const finish=value=>{if(done)return;done=true;navigator.serviceWorker.removeEventListener('controllerchange',changed);clearTimeout(timer);resolve(value);};const changed=()=>finish(true);const timer=setTimeout(()=>finish(false),timeoutMs);navigator.serviceWorker.addEventListener('controllerchange',changed);});}
  async function checkForUiUpgrade(){if(!('serviceWorker'in navigator))return false;const registration=await navigator.serviceWorker.getRegistration();if(!registration)return false;const controllerChange=waitForControllerChange();await registration.update().catch(()=>{});if(registration.waiting)registration.waiting.postMessage({type:'SKIP_WAITING'});const changed=await controllerChange;if(changed&&!state.reloadingForUpgrade){state.reloadingForUpgrade=true;const note=$('dashboardRefreshNote');if(note)note.textContent='New app version detected. Reloading the UI…';setTimeout(()=>window.location.reload(),120);return true;}return false;}

  async function refreshDashboard(){
    const button=$('dashboardRefreshBtn'),strip=$('dashboardHealthStrip'),note=$('dashboardRefreshNote');if(button){button.disabled=true;button.classList.add('refreshing');button.querySelector('span').textContent='Checking…';}if(strip){strip.classList.remove('healthy','warn','error');strip.classList.add('checking');strip.querySelector('.health-text').textContent='Refreshing UI & validating data…';}if(note)note.textContent='Checking stored data and looking for a newer app/UI version…';
    try{const loaded=safeLoadData(),result=validateIntegrity(loaded.data,loaded.parseError);state.lastRefresh=new Date();if(typeof window.displayEntries==='function')window.displayEntries();else if(typeof window.computeStats==='function')window.computeStats(loaded.data);updateHealthUI(result);if(button)button.querySelector('span').textContent=result.level==='healthy'?'Updated':'Review Data';if(note)note.textContent=result.level==='healthy'?'Dashboard calculations and data checks are current. Checking for UI upgrade…':'Data refreshed. Open Data Health for the recommended corrective action.';const upgradeApplied=await checkForUiUpgrade();if(upgradeApplied)return;if(note)note.textContent=result.level==='healthy'?'Dashboard, data and UI version are current.':'Data refreshed. Resolve the listed review items, then press Refresh again.';setTimeout(()=>{if(button){button.disabled=false;button.classList.remove('refreshing');button.querySelector('span').textContent='Refresh';}},1200);}catch(error){state.lastRefresh=new Date();updateHealthUI({level:'error',issues:[{type:'error',text:'Refresh failed.',detail:'The current session could not complete its refresh checks.',action:'Close and reopen Fuel Tracker. If the issue continues, restore your latest known-good Master DB backup.',target:'backup'}],latest:null,count:0});if(note)note.textContent='Refresh could not complete. Open Data Health for recovery steps.';if(button){button.disabled=false;button.classList.remove('refreshing');button.querySelector('span').textContent='Retry';}}
  }

  function attachInteractions(){
    document.querySelectorAll('.dashboard-switch-btn').forEach(btn=>btn.addEventListener('click',()=>setView(btn.dataset.dashboardView)));document.querySelectorAll('.dashboard-common-tab').forEach(btn=>btn.addEventListener('click',()=>setCommonPeriod(btn.dataset.commonPeriod)));$('dashboardRefreshBtn')?.addEventListener('click',refreshDashboard);
    const healthStrip=$('dashboardHealthStrip');const toggleDetails=()=>{const details=$('dashboardHealthDetails');if(!details)return;details.hidden=!details.hidden;healthStrip?.setAttribute('aria-expanded',details.hidden?'false':'true');};healthStrip?.addEventListener('click',toggleDetails);healthStrip?.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();toggleDetails();}});$('dashboardHealthDetails')?.addEventListener('click',event=>{const btn=event.target.closest('[data-health-action]');if(btn)scrollToTarget(btn.dataset.healthAction);});
    const stage=$('dashboardViewStage');let startX=null;stage?.addEventListener('touchstart',event=>{startX=event.changedTouches?.[0]?.clientX??null;},{passive:true});stage?.addEventListener('touchend',event=>{if(startX===null)return;const endX=event.changedTouches?.[0]?.clientX??startX,dx=endX-startX;startX=null;if(Math.abs(dx)<55)return;if(dx<0&&state.view==='efficiency')setView('spending');else if(dx>0&&state.view==='spending')setView('efficiency');},{passive:true});window.addEventListener('storage',event=>{if(event.key===storageKey())refreshDashboard();});
  }
  function init(){if(!buildUI())return;attachInteractions();setView('efficiency');setCommonPeriod('14');const loaded=safeLoadData();state.lastRefresh=new Date();updateHealthUI(validateIntegrity(loaded.data,loaded.parseError));}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
